1666609879040	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1666609879041	Sync.Telemetry	INFO	Early submission of sync telemetry due to changed IDs/NodeType
1666612103186	Sync.SyncScheduler	DEBUG	Going to sleep, doing a quick sync.
1666612103187	Sync.Service	DEBUG	User-Agent: Firefox/105.0.2 (Linux x86_64) FxSync/1.107.0.20221005092643.desktop
1666612103187	Sync.Service	INFO	Starting sync at 2022-10-24 19:48:23 in browser session icziCpva8Rkw
1666612103187	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1666612103193	Sync.Status	INFO	Resetting Status.
1666612103193	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1666612103193	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1666612103193	FirefoxAccounts	DEBUG	getOAuthToken enter
1666612103194	FirefoxAccounts	TRACE	getCachedToken returning cached token
1666612103194	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1666612103194	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1666612103233	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1666612103233	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 489\"  data: no]"}
1666612103248	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/198175302/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1666612103248	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1666612103248	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1666612103248	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1666612103249	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=reschedule)
1666612103252	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
